apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-test
spec:
  image: couchbase/server:6.6.0
  paused: false
  antiAffinity: true
  softwareUpdateNotifications: true
  cluster:
    clusterName: cb-test
    dataServiceMemoryQuota: 3Gi
    indexServiceMemoryQuota: 1Gi
    searchServiceMemoryQuota: 1Gi
    indexStorageSetting: plasma
    autoFailoverTimeout: 360s
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120s
    autoFailoverServerGroup: false
    autoCompaction:
      databaseFragmentationThreshold:
        percent: 30
      viewFragmentationThreshold:
        percent: 30
      parallelCompaction: false
      timeWindow:
        start: 02:00
        end: 06:00
        abortCompactionOutsideWindow: true
      tombstonePurgeInterval: 72h
  security:
    adminSecret: cb-admin-secret
    rbac:
      managed: true
      selector:
        matchLabels:
          cluster: cb-test
  networking:
    exposeAdminConsole: true
    adminConsoleServices:
    - data
    adminConsoleServiceType: NodePort
    exposedFeatures:
      - xdcr
      - client
    exposedFeatureServiceType: NodePort
  logging:
    logRetentionTime: 604800s
    logRetentionCount: 20
  servers:
  - size: 3
    name: all_services
    services:
    - data
    - index
    - query
    - search
    resources:
      limits:
        cpu: 4000m
        memory: 6Gi
      requests:
        cpu: 3000m
        memory: 5Gi
    volumeMounts:
      default: cb-default-pvc
      data: cb-data-pvc
      index: cb-index-pvc
    pod:
      metadata:
        labels:
          couchbase_services: all
        annotations:
          couchbase.acme.com: production
  buckets:
    managed: true
    selector:
      matchLabels:
        cluster: cb-test
  volumeClaimTemplates:
  - metadata:
      name: cb-index-pvc
    spec:
      storageClassName: standard-lazy-bound
      resources:
        requests:
          storage: 16Gi
  - metadata:
      name: cb-data-pvc
    spec:
      storageClassName: standard-lazy-bound
      resources:
        requests:
          storage: 96Gi
  - metadata:
      name: cb-default-pvc
    spec:
      storageClassName: standard-lazy-bound
      resources:
        requests:
          storage: 16Gi