apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-lazy-bound
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true