apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: live
  labels:
    cluster: cb-test
spec:
  memoryQuota: 2Gi
  replicas: 1
  ioPriority: high
  evictionPolicy: valueOnly
  enableFlush: true
  enableIndexReplica: false