kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: couchbase
resources:
- _bucket_secret.yaml
- _live_bucket.yaml
- _offline_bucket.yaml
- _bucket_cb-group.yaml
- _bucket_cb-user.yaml
- _bucket_cb-rbac.yaml
